// <auto-generated />
using CardGameStatsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TDDBackendStats.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250925204441_RenameLayerReachedToDifficultyLevel")]
    partial class RenameLayerReachedToDifficultyLevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TDDBackendStats.Models.CardPickStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TimesPicked")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CardPickStats");
                });

            modelBuilder.Entity("TDDBackendStats.Models.GameStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CardsPicked")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CharmsPicked")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DeckSize")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("EnemyThatKilled")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExtractionsUsed")
                        .HasColumnType("int");

                    b.Property<string>("RelicsPicked")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StartingClass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SteamName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Win")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("GameStats");
                });
#pragma warning restore 612, 618
        }
    }
}
